// <auto-generated />
using System;
using KnowledgeSpace.BackendServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KnowledgeSpace.BackendServer.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201011090023_AllowNullColumnNguoiTaoAllTable")]
    partial class AllowNullColumnNguoiTaoAllTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.KnowledgeBaseSequence", "'KnowledgeBaseSequence', '', '1', '1', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasMaxLength(4);

                    b.Property<int?>("KnowledgeBaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int?>("NumberOfTickets")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Command", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.CommandInFunction", b =>
                {
                    b.Property<string>("CommandId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FunctionId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CommandId", "FunctionId");

                    b.ToTable("CommandInFunctions");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("KnowledgeBaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUserId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ReplyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DMTonGiao", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DMTonGiao");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmCapDonVi", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmCapDonVi");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmCapHoc", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmCapHoc");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmCumThiDua", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmCumThiDua");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmDanToc", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TenGoiKhac")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmDanToc");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmHuyen", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DmTinhMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamHocMa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DmTinhMa");

                    b.HasIndex("NamHocMa");

                    b.ToTable("DmHuyen");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmKhoi", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DmCapHocMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaCapHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiLop")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DmCapHocMa");

                    b.ToTable("DmKhoi");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmLoaiCanBo", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("IsC1")
                        .HasColumnType("int");

                    b.Property<int?>("IsC2")
                        .HasColumnType("int");

                    b.Property<int?>("IsC3")
                        .HasColumnType("int");

                    b.Property<int?>("IsGdtx")
                        .HasColumnType("int");

                    b.Property<int?>("IsMN")
                        .HasColumnType("int");

                    b.Property<string>("MaNhomCanBo")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmLoaiCanBo");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmLoaiHinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IsC1")
                        .HasColumnType("int");

                    b.Property<int?>("IsC2")
                        .HasColumnType("int");

                    b.Property<int?>("IsC3")
                        .HasColumnType("int");

                    b.Property<int?>("IsGdtx")
                        .HasColumnType("int");

                    b.Property<int?>("IsMN")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DmLoaiHinh");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmLoaiKhuyetTat", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmLoaiKhuyetTat");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmLoaiTruong", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IsC1")
                        .HasColumnType("int");

                    b.Property<int?>("IsC2")
                        .HasColumnType("int");

                    b.Property<int?>("IsC3")
                        .HasColumnType("int");

                    b.Property<int?>("IsGdtx")
                        .HasColumnType("int");

                    b.Property<int?>("IsMN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmLoaiTruong");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmLyDoNghiViec", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmLyDoNghiViec");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmLyDoThoiHoc", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmLyDoThoiHoc");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmMonDayGV", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IsC1")
                        .HasColumnType("int");

                    b.Property<int?>("IsC2")
                        .HasColumnType("int");

                    b.Property<int?>("IsC3")
                        .HasColumnType("int");

                    b.Property<int?>("IsGdtx")
                        .HasColumnType("int");

                    b.Property<int?>("IsMN")
                        .HasColumnType("int");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmMonDayGV");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmMonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DmCapHocMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IsMonTC")
                        .HasColumnType("int");

                    b.Property<int>("KieuMonHoc")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaCapHoc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMon")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<int?>("NamHocMa")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DmCapHocMa");

                    b.HasIndex("NamHocMa");

                    b.ToTable("DmMonHoc");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmNgach", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("IsC1")
                        .HasColumnType("int");

                    b.Property<int?>("IsC2")
                        .HasColumnType("int");

                    b.Property<int?>("IsC3")
                        .HasColumnType("int");

                    b.Property<int?>("IsGDTX")
                        .HasColumnType("int");

                    b.Property<int?>("IsMN")
                        .HasColumnType("int");

                    b.Property<string>("LoaiNgach")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNgach")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmNgach");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmNhomCanBo", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("IsC1")
                        .HasColumnType("int");

                    b.Property<int?>("IsC2")
                        .HasColumnType("int");

                    b.Property<int?>("IsC3")
                        .HasColumnType("int");

                    b.Property<int?>("IsGDTX")
                        .HasColumnType("int");

                    b.Property<int?>("IsMN")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmNhomCanBo");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmNhomCapHoc", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DSCap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Ma");

                    b.ToTable("DmNhomCapHoc");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmNhomTuoiMN", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaNhomTre")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Ma");

                    b.ToTable("DmNhomTuoiMN");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmNuoc", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmNuoc");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmSoBuoiHocTrenTuan", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmSoBuoiHocTrenTuan");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmTinh", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmTinh");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmTrangThaiCanBo", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmTrangThaiCanBo");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmTrangThaiHocSinh", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaChuyenDenChuyenDi")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmTrangThaiHocSinh");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmTrinhDoChuyenMonNghiepVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DmTrinhDoChuyenMonNghiepVu");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmVung", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Ma");

                    b.ToTable("DmVung");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmXa", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DmHuyenId")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("DmTinhMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("IdHuyen")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DmHuyenId");

                    b.HasIndex("DmTinhMa");

                    b.ToTable("DmXa");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Function", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.HocSinh", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("IdPhongGD")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("IdTruong")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaCapHoc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDanToc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaGioiTinh")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLyDoThoiHoc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaPhongGD")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaQuocTich")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoBuoiHocTrenTuan")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTonGiao")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTrangThai")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTruong")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("PhongGDId")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("SoGDMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<decimal?>("TruongId")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("PhongGDId");

                    b.HasIndex("SoGDMa");

                    b.HasIndex("TruongId");

                    b.ToTable("HocSinh");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.KnowledgeBase", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Labels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfComments")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfReports")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfVotes")
                        .HasColumnType("int");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Problem")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("StepToReproduce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.Property<string>("Workaround")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBases");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Label", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.LabelInKnowledgeBase", b =>
                {
                    b.Property<string>("LabelId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("KnowledgeBaseId")
                        .HasColumnType("int");

                    b.HasKey("LabelId", "KnowledgeBaseId");

                    b.ToTable("LabelInKnowledgeBases");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Lop", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("IdPhongGD")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("IdTruong")
                        .HasColumnType("numeric(18,0)");

                    b.Property<int?>("IsLopGhep")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaCapHoc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKhoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaNhomTuoiMN")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaPhongGD")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoBuoiHocTrenTuan")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTruong")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("PhongGDId")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("SoGDMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<decimal?>("TruongId")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("PhongGDId");

                    b.HasIndex("SoGDMa");

                    b.HasIndex("TruongId");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.NamHoc", b =>
                {
                    b.Property<int>("Ma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasMaxLength(20)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Ma");

                    b.ToTable("NamHoc");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.NhanSu", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("IdPhongGD")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal>("IdTruong")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaCapHoc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDanToc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaGioiTinh")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLoaiCanBo")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaNgach")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNhomCanBo")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaPhongGD")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaQuocTich")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTonGiao")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTrangThai")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTrinhDoChuyenMon")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTruong")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("Date");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("PhongGDId")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("SoGDMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<decimal?>("TruongId")
                        .HasColumnType("numeric(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("PhongGDId");

                    b.HasIndex("SoGDMa");

                    b.HasIndex("TruongId");

                    b.ToTable("NhanSu");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Permission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FunctionId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("CommandId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("RoleId", "FunctionId", "CommandId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.PhongGD", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("IdHuyen")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaSoGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaVung")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("SoGDMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("SoGDMa");

                    b.ToTable("PhongGD");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<int?>("KnowledgeBaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportUserId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.SoGD", b =>
                {
                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MaCumThiDua")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTinh")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Ma");

                    b.ToTable("SoGD");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Truong", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DSCapHoc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("IdHuyen")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("IdPhongGD")
                        .HasColumnType("numeric(18,0)");

                    b.Property<int?>("IsCapGDTX")
                        .HasColumnType("int");

                    b.Property<int?>("IsCapMN")
                        .HasColumnType("int");

                    b.Property<int?>("IsCapTH")
                        .HasColumnType("int");

                    b.Property<int?>("IsCapTHCS")
                        .HasColumnType("int");

                    b.Property<int?>("IsCapTHPT")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MaHuyen")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLoaiHinh")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLoaiTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaNhomCapHoc")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaPhongGD")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoGD")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaVung")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NguoiSua")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("NguoiTao")
                        .HasColumnType("numeric(18,0)");

                    b.Property<decimal?>("PhongGDId")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("SoGDMa")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("PhongGDId");

                    b.HasIndex("SoGDMa");

                    b.ToTable("Truong");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int?>("NumberOfKnowledgeBases")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfReports")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfVotes")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Vote", b =>
                {
                    b.Property<int>("KnowledgeBaseId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("KnowledgeBaseId", "UserId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmHuyen", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.DmTinh", "DmTinh")
                        .WithMany("DmHuyen")
                        .HasForeignKey("DmTinhMa");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.NamHoc", "NamHoc")
                        .WithMany()
                        .HasForeignKey("NamHocMa");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmKhoi", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.DmCapHoc", "DmCapHoc")
                        .WithMany("DmKhoi")
                        .HasForeignKey("DmCapHocMa");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmMonHoc", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.DmCapHoc", "DmCapHoc")
                        .WithMany()
                        .HasForeignKey("DmCapHocMa");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.NamHoc", "NamHoc")
                        .WithMany()
                        .HasForeignKey("NamHocMa");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.DmXa", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.DmHuyen", "DmHuyen")
                        .WithMany()
                        .HasForeignKey("DmHuyenId");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.DmTinh", "DmTinh")
                        .WithMany()
                        .HasForeignKey("DmTinhMa");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.HocSinh", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.PhongGD", "PhongGD")
                        .WithMany()
                        .HasForeignKey("PhongGDId");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.SoGD", "SoGD")
                        .WithMany()
                        .HasForeignKey("SoGDMa");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.Truong", "Truong")
                        .WithMany()
                        .HasForeignKey("TruongId");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Lop", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.PhongGD", "PhongGD")
                        .WithMany()
                        .HasForeignKey("PhongGDId");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.SoGD", "SoGD")
                        .WithMany()
                        .HasForeignKey("SoGDMa");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.Truong", "Truong")
                        .WithMany()
                        .HasForeignKey("TruongId");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.NhanSu", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.PhongGD", "PhongGD")
                        .WithMany()
                        .HasForeignKey("PhongGDId");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.SoGD", "SoGD")
                        .WithMany()
                        .HasForeignKey("SoGDMa");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.Truong", "Truong")
                        .WithMany()
                        .HasForeignKey("TruongId");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.PhongGD", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.SoGD", "SoGD")
                        .WithMany()
                        .HasForeignKey("SoGDMa");
                });

            modelBuilder.Entity("KnowledgeSpace.BackendServer.Data.Entities.Truong", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.PhongGD", "PhongGD")
                        .WithMany()
                        .HasForeignKey("PhongGDId");

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.SoGD", "SoGD")
                        .WithMany()
                        .HasForeignKey("SoGDMa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KnowledgeSpace.BackendServer.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
